#if UNITY_IOS && QBOT_UTILITY_PUSH_NOTIFICATIONS
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;

namespace qbot.Utility
{
    public static partial class IOSPostProcessBuilder
    {
        [PostProcessBuild]
        public static void OnPostProcessBuildPushNotification(BuildTarget target, string pathToBuiltProject)
        {
            AddPushNotificationCapability(pathToBuiltProject);
        }

        private static void AddPushNotificationCapability(string pathToBuiltProject)
        {
            // Initialize PBXProject
            var projectPath = PBXProject.GetPBXProjectPath(pathToBuiltProject);
            var pbxProject = new PBXProject();
            pbxProject.ReadFromFile(projectPath);

            // Get Main target GUID
            var mainTargetGuid = pbxProject.GetUnityMainTargetGuid();

            // Check if there's already an entitlements file created and use it. If not, create a new file called Example.entitlements
            var entitlementsFile = pbxProject.GetBuildPropertyForAnyConfig(mainTargetGuid, "CODE_SIGN_ENTITLEMENTS") ?? "autogenerated.entitlements";

            // Initialize ProjectCapabilityManager and add 'Push Notifications' capability
            var capabilityManager = new ProjectCapabilityManager(projectPath, entitlementsFile, targetGuid: mainTargetGuid);
            capabilityManager.AddPushNotifications(true);
            capabilityManager.AddBackgroundModes(BackgroundModesOptions.RemoteNotifications);

            // Call WriteToFile to save the changes to project file
            capabilityManager.WriteToFile();
        }
    }
}
#endif